[project]
name = "uconsole-sleep"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["inotify-simple>=1.3.5"]

[tool.uv.sources]
sleep-power-control = { path = "sleep-power-control" }
sleep-remap-powerkey = { path = "sleep-remap-powerkey" }
